//! Lockfile rendering for resolved desired state.

use std::path::{Path, PathBuf};

use crate::error::{EngineError, Result};
use serde::{Deserialize, Serialize};

use crate::actions::sync::SyncItem;
use crate::infra::hashing::Hashing;
use crate::infra::paths::PathOps;
use crate::platform::System;
use crate::platform::{PlatformId, current_platform};
use crate::specs::agents::{
    NormalizedSkill, NormalizedSkillSource, managed_skill_dir_name, normalize_agents,
};
use crate::specs::item::{BackendId, ItemKind};
use crate::specs::toml::StillConfig;

/// Project lockfile name written next to `still.toml`.
pub const LOCKFILE_NAME: &str = "still.lock.toml";

/// Returns the lockfile path for a resolved config file.
pub fn lockfile_path(config_path: &Path) -> PathBuf {
    config_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(LOCKFILE_NAME)
}

/// Renders a deterministic TOML lockfile from sync items.
pub fn render_lockfile(items: &[SyncItem]) -> String {
    render_lockfile_entries(&lockfile_items(items))
}

/// Renders a lockfile that preserves valid entries for platforms other than the active host.
pub fn render_merged_lockfile(existing: Option<&str>, items: &[SyncItem]) -> String {
    render_merged_lockfile_entries(existing, lockfile_items(items))
}

/// Renders a merged lockfile including non-install agent skill state.
pub fn render_merged_lockfile_for_config(
    existing: Option<&str>,
    items: &[SyncItem],
    config: &StillConfig,
    config_path: &Path,
) -> Result<String> {
    let mut entries = lockfile_items(items);
    entries.extend(agent_skill_lockfile_items(config, config_path)?);
    Ok(render_merged_lockfile_entries(existing, entries))
}

fn render_merged_lockfile_entries(
    existing: Option<&str>,
    current_entries: Vec<LockfileItem>,
) -> String {
    let platform = current_platform().to_string();
    let mut entries = match existing {
        Some(existing) => parse_lockfile_items(existing),
        None => Vec::new(),
    };
    entries.retain(|item| item.platform != platform);
    entries.extend(current_entries);
    render_lockfile_entries(&entries)
}

/// Validates a lockfile against Still's typed lockfile schema.
pub fn validate_lockfile(input: &str) -> Result<()> {
    let lockfile = toml::from_str::<Lockfile>(input)?;
    for (index, item) in lockfile.items.iter().enumerate() {
        validate_lockfile_item(index + 1, item)?;
    }
    Ok(())
}

fn render_lockfile_entries(items: &[LockfileItem]) -> String {
    let mut output = String::from("# Generated by still. Do not edit by hand.\n\n");
    if items.is_empty() {
        output.push_str("# no resolved items\n");
        return output;
    }

    output.push_str(
        &toml::to_string_pretty(&Lockfile {
            items: items.to_vec(),
        })
        .expect("lockfile serialization should not fail for string-only values"),
    );
    output
}

fn lockfile_items(items: &[SyncItem]) -> Vec<LockfileItem> {
    items
        .iter()
        .map(|item| {
            let source = source_identity(item);
            LockfileItem {
                kind: item.kind.to_string(),
                name: item.spec.name.clone(),
                platform: current_platform().to_string(),
                version: item.spec.version.to_string(),
                backend: item.spec.backend.as_ref().map(ToString::to_string),
                source: source.clone(),
                checksum: desired_state_checksum(item, &source),
                outputs: vec![expected_output_path(item).display().to_string()],
                linked_executables: Vec::new(),
            }
        })
        .collect()
}

fn agent_skill_lockfile_items(
    config: &StillConfig,
    config_path: &Path,
) -> Result<Vec<LockfileItem>> {
    let Some(agents) = config.agents.clone() else {
        return Ok(Vec::new());
    };
    let agents = normalize_agents(agents)?;
    let root = config_path.parent().unwrap_or_else(|| Path::new("."));
    agents
        .skills
        .iter()
        .map(|skill| agent_skill_lockfile_item(skill, root))
        .collect()
}

fn agent_skill_lockfile_item(skill: &NormalizedSkill, root: &Path) -> Result<LockfileItem> {
    let source = agent_skill_source_identity(skill);
    let version = agent_skill_version(skill);
    let output = root
        .join(".agents")
        .join("skills")
        .join(managed_skill_dir_name(&skill.name)?);
    Ok(LockfileItem {
        kind: "agent-skill".to_string(),
        name: skill.name.clone(),
        platform: current_platform().to_string(),
        version: version.clone(),
        backend: None,
        checksum: agent_skill_checksum(skill, &source, &version),
        source,
        outputs: vec![output.display().to_string()],
        linked_executables: Vec::new(),
    })
}

fn agent_skill_source_identity(skill: &NormalizedSkill) -> String {
    match &skill.source {
        NormalizedSkillSource::Official { name, .. } => format!("official:{name}"),
        NormalizedSkillSource::GitHub { path, .. } => format!("github:{path}"),
        NormalizedSkillSource::Url { url, .. } => format!("url:{url}"),
    }
}

fn agent_skill_version(skill: &NormalizedSkill) -> String {
    match &skill.source {
        NormalizedSkillSource::Official { version, .. }
        | NormalizedSkillSource::GitHub { version, .. }
        | NormalizedSkillSource::Url { version, .. } => {
            version.clone().unwrap_or_else(|| "latest".to_string())
        }
    }
}

#[derive(Debug, Default, Deserialize, Serialize)]
struct Lockfile {
    #[serde(default)]
    items: Vec<LockfileItem>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
struct LockfileItem {
    kind: String,
    name: String,
    platform: String,
    version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    backend: Option<String>,
    source: String,
    checksum: String,
    #[serde(default)]
    outputs: Vec<String>,
    #[serde(default)]
    linked_executables: Vec<String>,
}

fn parse_lockfile_items(input: &str) -> Vec<LockfileItem> {
    toml::from_str::<Lockfile>(input)
        .map(|lockfile| lockfile.items)
        .unwrap_or_default()
}

fn validate_lockfile_item(index: usize, item: &LockfileItem) -> Result<()> {
    if item.name.trim().is_empty() {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an empty name"
        )));
    }
    if item.kind != "agent-skill" {
        item.kind.parse::<ItemKind>().map_err(|err| {
            EngineError::message(format!("lockfile item {index} has invalid kind: {err}"))
        })?;
    }
    item.platform.parse::<PlatformId>().map_err(|err| {
        EngineError::message(format!("lockfile item {index} has invalid platform: {err}"))
    })?;
    if item.version.trim().is_empty() {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an empty version"
        )));
    }
    if let Some(backend) = &item.backend {
        backend.parse::<BackendId>().map_err(|err| {
            EngineError::message(format!("lockfile item {index} has invalid backend: {err}"))
        })?;
    }
    if item.source.trim().is_empty() {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an empty source"
        )));
    }
    if item.checksum.trim().is_empty() {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an empty checksum"
        )));
    }
    if !is_sha256_hex(&item.checksum) {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an invalid checksum"
        )));
    }
    if item.outputs.is_empty() {
        return Err(EngineError::message(format!(
            "lockfile item {index} has no expected outputs"
        )));
    }
    if item.outputs.iter().any(|output| output.trim().is_empty()) {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an empty output path"
        )));
    }
    if item
        .linked_executables
        .iter()
        .any(|link| link.trim().is_empty())
    {
        return Err(EngineError::message(format!(
            "lockfile item {index} has an empty linked executable path"
        )));
    }
    Ok(())
}

fn is_sha256_hex(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn expected_output_path(item: &SyncItem) -> PathBuf {
    let root = match item.kind {
        ItemKind::Tool => System::tool_dir(),
        ItemKind::Package => System::root_dir().join("receipts").join("packages"),
        ItemKind::App => System::root_dir().join("receipts").join("apps"),
    };
    root.join(&item.spec.name).join(item.spec.version.as_str())
}

fn source_identity(item: &SyncItem) -> String {
    item.spec
        .backend
        .as_ref()
        .map(|backend| format!("backend:{backend}"))
        .unwrap_or_else(|| "backend:auto".to_string())
}

fn desired_state_checksum(item: &SyncItem, source: &str) -> String {
    let backend = item
        .spec
        .backend
        .as_ref()
        .map(ToString::to_string)
        .unwrap_or_else(|| "auto".to_string());
    let identity = format!(
        "{}\n{}\n{}\n{}\n{}\n{}\n{}\n",
        item.kind,
        item.spec.name,
        current_platform(),
        item.spec.version,
        backend,
        source,
        item.desired_state
    );
    Hashing::sha256(identity.as_bytes())
}

fn agent_skill_checksum(skill: &NormalizedSkill, source: &str, version: &str) -> String {
    let identity = format!(
        "agent-skill\n{}\n{}\n{}\n{}\n{}\n{:?}\n{:?}\n{:?}\n{}\n",
        skill.name,
        current_platform(),
        version,
        source,
        skill.auto,
        skill.tools,
        skill.packages,
        skill.apps,
        agent_skill_source_identity(skill)
    );
    Hashing::sha256(identity.as_bytes())
}

#[cfg(test)]
mod tests {
    use crate::specs::item::ItemKind;
    use crate::specs::toml::parse_still_toml;

    use super::*;

    #[test]
    fn renders_items_in_order() {
        let output = render_lockfile(&[
            item(ItemKind::Tool, "rust@stable@rustup"),
            item(ItemKind::Package, "openssl"),
        ]);

        assert!(output.contains("kind = \"tool\""));
        assert!(output.contains("name = \"rust\""));
        assert!(output.contains(&format!("platform = \"{}\"", current_platform())));
        assert!(output.contains("backend = \"rustup\""));
        assert!(output.contains("source = \"backend:rustup\""));
        assert!(output.contains("checksum = \""));
        assert!(output.contains("outputs = ["));
        assert!(output.contains("linked_executables = []"));
        assert!(output.contains("kind = \"package\""));
    }

    #[test]
    fn renders_agent_skills_as_lockfile_items() {
        let config = parse_still_toml(
            r#"
            [agents.skills]
            rust-review = { url = "https://example.com/rust-review", version = "v1.2.3", auto = true, tools = ["cargo-nextest"] }
            "#,
        )
        .unwrap();
        let config_path = Path::new("/repo/still.toml");

        let output = render_merged_lockfile_for_config(None, &[], &config, config_path).unwrap();

        assert!(output.contains("kind = \"agent-skill\""));
        assert!(output.contains("name = \"rust-review\""));
        assert!(output.contains("version = \"v1.2.3\""));
        assert!(output.contains("source = \"url:https://example.com/rust-review\""));
        assert!(output.contains("outputs = [\"/repo/.agents/skills/rust-review\"]"));
        validate_lockfile(&output).unwrap();
    }

    #[test]
    fn checksum_changes_when_backend_changes() {
        let rustup = item(ItemKind::Tool, "rust@stable@rustup");
        let mise = item(ItemKind::Tool, "rust@stable@mise");

        assert_ne!(
            desired_state_checksum(&rustup, &source_identity(&rustup)),
            desired_state_checksum(&mise, &source_identity(&mise))
        );
    }

    #[test]
    fn checksum_changes_when_desired_state_metadata_changes() {
        let base = item(ItemKind::Tool, "rust@stable@rustup");
        let mut with_component = item(ItemKind::Tool, "rust@stable@rustup");
        with_component.desired_state = "tool:rust:components=[clippy]".to_string();

        assert_ne!(
            desired_state_checksum(&base, &source_identity(&base)),
            desired_state_checksum(&with_component, &source_identity(&with_component))
        );
    }

    #[test]
    fn merged_lockfile_preserves_other_platform_entries() {
        let other_platform = if current_platform().to_string() == "linux" {
            "windows"
        } else {
            "linux"
        };
        let existing = format!(
            r#"
            [[items]]
            kind = "package"
            name = "fd-find"
            platform = "{other_platform}"
            version = "latest"
            source = "backend:auto"
            checksum = "old"
            outputs = ["/still/packages/fd-find/latest"]
            linked_executables = []
            "#
        );

        let output = render_merged_lockfile(
            Some(&existing),
            &[item(ItemKind::Tool, "rust@stable@rustup")],
        );

        assert!(output.contains(&format!("platform = \"{other_platform}\"")));
        assert!(output.contains("name = \"fd-find\""));
        assert!(output.contains(&format!("platform = \"{}\"", current_platform())));
        assert!(output.contains("name = \"rust\""));
    }

    #[test]
    fn merged_lockfile_replaces_current_platform_entries() {
        let platform = current_platform();
        let existing = format!(
            r#"
            [[items]]
            kind = "tool"
            name = "old-rust"
            platform = "{platform}"
            version = "old"
            source = "backend:auto"
            checksum = "old"
            outputs = ["/still/tools/old-rust/old"]
            linked_executables = []
            "#
        );

        let output = render_merged_lockfile(
            Some(&existing),
            &[item(ItemKind::Tool, "rust@stable@rustup")],
        );

        assert!(!output.contains("old-rust"));
        assert!(output.contains("name = \"rust\""));
    }

    #[test]
    fn validates_typed_lockfile_items() {
        let content = format!(
            r#"
            [[items]]
            kind = "tool"
            name = "rust"
            platform = "{}"
            version = "stable"
            backend = "rustup"
            source = "backend:rustup"
            checksum = "{}"
            outputs = ["/still/tools/rust/stable"]
            linked_executables = []
            "#,
            current_platform(),
            "a".repeat(64)
        );

        validate_lockfile(&content).unwrap();
    }

    #[test]
    fn rejects_invalid_lockfile_items() {
        let content = r#"
            [[items]]
            kind = "plugin"
            name = "rust"
            platform = "plan9"
            version = "stable"
            source = "backend:auto"
            checksum = "{}"
        "#;
        let content = content.replace("{}", &"a".repeat(64));

        let err = validate_lockfile(&content).unwrap_err();

        assert!(err.to_string().contains("invalid kind"));
    }

    #[test]
    fn rejects_invalid_lockfile_checksums() {
        let content = format!(
            r#"
            [[items]]
            kind = "package"
            name = "openssl"
            platform = "{}"
            version = "latest"
            source = "backend:auto"
            checksum = "abc123"
            "#,
            current_platform()
        );

        let err = validate_lockfile(&content).unwrap_err();

        assert!(err.to_string().contains("invalid checksum"));
    }

    #[test]
    fn rejects_lockfile_items_without_outputs() {
        let content = format!(
            r#"
            [[items]]
            kind = "package"
            name = "openssl"
            platform = "{}"
            version = "latest"
            source = "backend:auto"
            checksum = "{}"
            outputs = []
            "#,
            current_platform(),
            "a".repeat(64)
        );

        let err = validate_lockfile(&content).unwrap_err();

        assert!(err.to_string().contains("no expected outputs"));
    }

    #[test]
    fn rejects_empty_lockfile_output_paths() {
        let content = format!(
            r#"
            [[items]]
            kind = "package"
            name = "openssl"
            platform = "{}"
            version = "latest"
            source = "backend:auto"
            checksum = "{}"
            outputs = [" "]
            linked_executables = [""]
            "#,
            current_platform(),
            "a".repeat(64)
        );

        let err = validate_lockfile(&content).unwrap_err();

        assert!(err.to_string().contains("empty output path"));
    }

    fn item(kind: ItemKind, spec: &str) -> SyncItem {
        let parsed: crate::specs::item::ItemSpec = spec.parse().unwrap();
        SyncItem {
            kind,
            logical_name: parsed.name.clone(),
            spec: parsed,
            tool: Default::default(),
            desired_state: spec.to_string(),
        }
    }
}
