//! Lockfile rendering for resolved desired state.

use std::path::{Path, PathBuf};

use crate::actions::sync::SyncItem;
use crate::platform::current_platform;

/// Project lockfile name written next to `still.toml`.
pub const LOCKFILE_NAME: &str = "still.lock.toml";

/// Returns the lockfile path for a resolved config file.
pub fn lockfile_path(config_path: &Path) -> PathBuf {
    config_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(LOCKFILE_NAME)
}

/// Renders a deterministic TOML lockfile from sync items.
pub fn render_lockfile(items: &[SyncItem]) -> String {
    let mut output = String::from("# Generated by still. Do not edit by hand.\n\n");
    if items.is_empty() {
        output.push_str("# no resolved items\n");
        return output;
    }

    for item in items {
        output.push_str("[[items]]\n");
        output.push_str(&format!("kind = \"{}\"\n", item.kind));
        output.push_str(&format!("name = \"{}\"\n", item.spec.name));
        output.push_str(&format!("platform = \"{}\"\n", current_platform()));
        output.push_str(&format!("version = \"{}\"\n", item.spec.version));
        if let Some(backend) = &item.spec.backend {
            output.push_str(&format!("backend = \"{}\"\n", backend));
        }
        output.push('\n');
    }
    output
}

#[cfg(test)]
mod tests {
    use crate::specs::item::ItemKind;

    use super::*;

    #[test]
    fn renders_items_in_order() {
        let output = render_lockfile(&[
            item(ItemKind::Tool, "rust@stable@rustup"),
            item(ItemKind::Package, "openssl"),
        ]);

        assert!(output.contains("kind = \"tool\""));
        assert!(output.contains("name = \"rust\""));
        assert!(output.contains(&format!("platform = \"{}\"", current_platform())));
        assert!(output.contains("backend = \"rustup\""));
        assert!(output.contains("kind = \"package\""));
    }

    fn item(kind: ItemKind, spec: &str) -> SyncItem {
        SyncItem {
            kind,
            spec: spec.parse().unwrap(),
        }
    }
}
