//! Lockfile rendering for resolved desired state.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::actions::sync::SyncItem;
use crate::platform::current_platform;
use crate::specs::item::ItemKind;
use crate::system::System;
use crate::utils::hashing::Hashing;
use crate::utils::paths::PathOps;

/// Project lockfile name written next to `still.toml`.
pub const LOCKFILE_NAME: &str = "still.lock.toml";

/// Returns the lockfile path for a resolved config file.
pub fn lockfile_path(config_path: &Path) -> PathBuf {
    config_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(LOCKFILE_NAME)
}

/// Renders a deterministic TOML lockfile from sync items.
pub fn render_lockfile(items: &[SyncItem]) -> String {
    render_lockfile_entries(&lockfile_items(items))
}

/// Renders a lockfile that preserves valid entries for platforms other than the active host.
pub fn render_merged_lockfile(existing: Option<&str>, items: &[SyncItem]) -> String {
    let platform = current_platform().to_string();
    let mut entries = match existing {
        Some(existing) => parse_lockfile_items(existing),
        None => Vec::new(),
    };
    entries.retain(|item| item.platform != platform);
    entries.extend(lockfile_items(items));
    render_lockfile_entries(&entries)
}

fn render_lockfile_entries(items: &[LockfileItem]) -> String {
    let mut output = String::from("# Generated by still. Do not edit by hand.\n\n");
    if items.is_empty() {
        output.push_str("# no resolved items\n");
        return output;
    }

    for item in items {
        output.push_str("[[items]]\n");
        output.push_str(&format!("kind = \"{}\"\n", toml_string(&item.kind)));
        output.push_str(&format!("name = \"{}\"\n", toml_string(&item.name)));
        output.push_str(&format!("platform = \"{}\"\n", toml_string(&item.platform)));
        output.push_str(&format!("version = \"{}\"\n", toml_string(&item.version)));
        if let Some(backend) = &item.backend {
            output.push_str(&format!("backend = \"{}\"\n", toml_string(backend)));
        }
        output.push_str(&format!("source = \"{}\"\n", toml_string(&item.source)));
        output.push_str(&format!("checksum = \"{}\"\n", toml_string(&item.checksum)));
        output.push_str(&format!("outputs = {}\n", toml_string_array(&item.outputs)));
        output.push_str(&format!(
            "linked_executables = {}\n",
            toml_string_array(&item.linked_executables)
        ));
        output.push('\n');
    }
    output
}

fn lockfile_items(items: &[SyncItem]) -> Vec<LockfileItem> {
    items
        .iter()
        .map(|item| {
            let source = source_identity(item);
            LockfileItem {
                kind: item.kind.to_string(),
                name: item.spec.name.clone(),
                platform: current_platform().to_string(),
                version: item.spec.version.to_string(),
                backend: item.spec.backend.as_ref().map(ToString::to_string),
                source: source.clone(),
                checksum: desired_state_checksum(item, &source),
                outputs: vec![expected_output_path(item).display().to_string()],
                linked_executables: Vec::new(),
            }
        })
        .collect()
}

#[derive(Debug, Default, Deserialize)]
struct Lockfile {
    #[serde(default)]
    items: Vec<LockfileItem>,
}

#[derive(Debug, Clone, Deserialize)]
struct LockfileItem {
    kind: String,
    name: String,
    platform: String,
    version: String,
    backend: Option<String>,
    source: String,
    checksum: String,
    #[serde(default)]
    outputs: Vec<String>,
    #[serde(default)]
    linked_executables: Vec<String>,
}

fn parse_lockfile_items(input: &str) -> Vec<LockfileItem> {
    toml_edit::de::from_str::<Lockfile>(input)
        .map(|lockfile| lockfile.items)
        .unwrap_or_default()
}

fn toml_string(value: &str) -> String {
    value
        .chars()
        .flat_map(|character| character.escape_default())
        .collect()
}

fn toml_string_array(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| format!("\"{}\"", toml_string(value)))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{values}]")
}

fn expected_output_path(item: &SyncItem) -> PathBuf {
    let root = match item.kind {
        ItemKind::Tool => System::tool_dir(),
        ItemKind::Package => System::root_dir().join("packages"),
        ItemKind::App => System::apps_dir(),
    };
    root.join(&item.spec.name).join(item.spec.version.as_str())
}

fn source_identity(item: &SyncItem) -> String {
    item.spec
        .backend
        .as_ref()
        .map(|backend| format!("backend:{backend}"))
        .unwrap_or_else(|| "backend:auto".to_string())
}

fn desired_state_checksum(item: &SyncItem, source: &str) -> String {
    let backend = item
        .spec
        .backend
        .as_ref()
        .map(ToString::to_string)
        .unwrap_or_else(|| "auto".to_string());
    let identity = format!(
        "{}\n{}\n{}\n{}\n{}\n{}\n",
        item.kind,
        item.spec.name,
        current_platform(),
        item.spec.version,
        backend,
        source
    );
    Hashing::sha256(identity.as_bytes())
}

#[cfg(test)]
mod tests {
    use crate::specs::item::ItemKind;

    use super::*;

    #[test]
    fn renders_items_in_order() {
        let output = render_lockfile(&[
            item(ItemKind::Tool, "rust@stable@rustup"),
            item(ItemKind::Package, "openssl"),
        ]);

        assert!(output.contains("kind = \"tool\""));
        assert!(output.contains("name = \"rust\""));
        assert!(output.contains(&format!("platform = \"{}\"", current_platform())));
        assert!(output.contains("backend = \"rustup\""));
        assert!(output.contains("source = \"backend:rustup\""));
        assert!(output.contains("checksum = \""));
        assert!(output.contains("outputs = ["));
        assert!(output.contains("linked_executables = []"));
        assert!(output.contains("kind = \"package\""));
    }

    #[test]
    fn checksum_changes_when_backend_changes() {
        let rustup = item(ItemKind::Tool, "rust@stable@rustup");
        let mise = item(ItemKind::Tool, "rust@stable@mise");

        assert_ne!(
            desired_state_checksum(&rustup, &source_identity(&rustup)),
            desired_state_checksum(&mise, &source_identity(&mise))
        );
    }

    #[test]
    fn merged_lockfile_preserves_other_platform_entries() {
        let other_platform = if current_platform().to_string() == "linux" {
            "windows"
        } else {
            "linux"
        };
        let existing = format!(
            r#"
            [[items]]
            kind = "package"
            name = "fd-find"
            platform = "{other_platform}"
            version = "latest"
            source = "backend:auto"
            checksum = "old"
            outputs = ["/still/packages/fd-find/latest"]
            linked_executables = []
            "#
        );

        let output = render_merged_lockfile(
            Some(&existing),
            &[item(ItemKind::Tool, "rust@stable@rustup")],
        );

        assert!(output.contains(&format!("platform = \"{other_platform}\"")));
        assert!(output.contains("name = \"fd-find\""));
        assert!(output.contains(&format!("platform = \"{}\"", current_platform())));
        assert!(output.contains("name = \"rust\""));
    }

    #[test]
    fn merged_lockfile_replaces_current_platform_entries() {
        let platform = current_platform();
        let existing = format!(
            r#"
            [[items]]
            kind = "tool"
            name = "old-rust"
            platform = "{platform}"
            version = "old"
            source = "backend:auto"
            checksum = "old"
            outputs = ["/still/tools/old-rust/old"]
            linked_executables = []
            "#
        );

        let output = render_merged_lockfile(
            Some(&existing),
            &[item(ItemKind::Tool, "rust@stable@rustup")],
        );

        assert!(!output.contains("old-rust"));
        assert!(output.contains("name = \"rust\""));
    }

    fn item(kind: ItemKind, spec: &str) -> SyncItem {
        SyncItem {
            kind,
            spec: spec.parse().unwrap(),
        }
    }
}
