id = "ripgrep"
name = "ripgrep"
description = "Fast recursive regex search"
homepage = "https://github.com/BurntSushi/ripgrep"
license = "MIT OR Unlicense"
versions = [
  "15.1.0",
  "15.0.0",
  "14.1.1",
]
latest = "15.1.0"
bins = ["rg"]
aliases = ["rg"]

preferred_sources = ["still", "aqua", "cargo", "homebrew"]

[sources.aqua]
type = "aqua-registry"
repo = "aquaproj/aqua-registry"
path = "pkgs/BurntSushi/ripgrep/registry.yaml"

[sources.cargo]
type = "cargo-crate"
crate = "ripgrep"

[sources.homebrew]
type = "homebrew-formula"
tap = "homebrew/core"
path = "Formula/r/ripgrep.rb"
