[package]
name = "still-source-homebrew"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "still_source_homebrew"
path = "lib.rs"

[features]
default = []
portable = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
still-source-kit = { path = "../../source-kit" }
