[package]
name = "still"
version.workspace = true
edition.workspace = true

[[bin]]
name = "still"
path = "src/main.rs"

[workspace]
members = ["crates/engine", "crates/tui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
engine = { path = "crates/engine" }
still_tui = { package = "still-tui", path = "crates/tui", optional = true }
tokio = { version = "1.48.0", features = ["full"] }

[dev-dependencies]
insta = "1.44.1"

[features]
default = []
tui = ["dep:still_tui"]

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"
